version: '3.8'

services:
  notebook:
    container_name: Model_training_notebooks
    labels:
      description: Contains 2 Jupyter files
      name: jupyter notebook
    ports:
      - "8888:8888"
    build: .

 
    
