version: '3.8'

services:
  pipeline_runner:
    container_name: stargazer-data-prepration
    build: .
    volumes:
      - ./0_ci_cd/development_server:/app/output
    environment:
      - OUTPUT_DIR=/app/output
    command: >
      sh -c "python data_preparation.py && mv github_repo_features_new.csv /app/output"
