version: '3.8'

services:
  pipeline_runner:
    container_name: model_training_pipeline
    labels:
      description: Runs pipeline.py to train and export best_model.pkl
      name: model training runner
    build: .
    command: >
      sh -c "python pipeline.py && mv best_model.pkl /home/appuser/stargazer-prediction-pipeline/0_ci_cd/development_server"
    volumes:
      - ./output:/home/appuser/stargazer-prediction-pipeline/0_ci_cd/development_server
