version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:2.9.4
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"

  knn-model:
  # Build directory should be adjusted to your folder structure !!
    build: .
    depends_on:
      - pulsar
