## Very important, If you were not part of this project, or you want to run a playbook within this project
## Make suure to change the following IPs to your own Dev & Prod !!

[dev]
devserver ansible_host=192.168.2.20 ansible_user=appuser ansible_ssh_private_key_file=/home/ubuntu/cluster-keys/cluster-key

[prod]
prodserver ansible_host=192.168.2.140 ansible_user=appuser ansible_ssh_private_key_file=/home/ubuntu/cluster-keys/cluster-key

[all:vars]
ansible_python_interpreter=/usr/bin/python3
